"""empty message

Revision ID: 991fb1677aa1
Revises: 
Create Date: 2019-08-20 11:49:06.616860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991fb1677aa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_name'), 'template', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_name'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
