"""templates table

Revision ID: fe6ea30bbcb7
Revises: 
Create Date: 2019-08-18 22:51:15.329422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6ea30bbcb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('template_data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_template_name'), 'template', ['template_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_template_name'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
